#include "vulkan_memory.h"
#include <limits>
namespace localimage::vulkan {
namespace { std::string vr(VkResult r){return std::to_string((int)r);} }
VulkanMemoryAllocator::VulkanMemoryAllocator(VkPhysicalDevice p,VkDevice d,uint32_t q):physical_(p),device_(d),queueFamily_(q){}
bool VulkanMemoryAllocator::findType(uint32_t bits,VkMemoryPropertyFlags props,uint32_t& idx,std::string& e)const{VkPhysicalDeviceMemoryProperties m{};vkGetPhysicalDeviceMemoryProperties(physical_,&m);for(uint32_t i=0;i<m.memoryTypeCount;++i)if((bits&(1u<<i))&&(m.memoryTypes[i].propertyFlags&props)==props){idx=i;return true;}e="no Vulkan memory type satisfies requested properties";return false;}
bool VulkanMemoryAllocator::create(VkDeviceSize size,VkBufferUsageFlags usage,VkMemoryPropertyFlags props,VkBuffer& b,VkDeviceMemory& mem,std::string&e)const{b=VK_NULL_HANDLE;mem=VK_NULL_HANDLE;if(!device_||!physical_||size==0){e="invalid Vulkan allocator state or zero size";return false;}VkBufferCreateInfo bi{VK_STRUCTURE_TYPE_BUFFER_CREATE_INFO};bi.size=size;bi.usage=usage;bi.sharingMode=VK_SHARING_MODE_EXCLUSIVE;if(queueFamily_!=VK_QUEUE_FAMILY_IGNORED){bi.queueFamilyIndexCount=1;bi.pQueueFamilyIndices=&queueFamily_;}VkResult r=vkCreateBuffer(device_,&bi,nullptr,&b);if(r!=VK_SUCCESS){e="vkCreateBuffer: "+vr(r);return false;}VkMemoryRequirements mr{};vkGetBufferMemoryRequirements(device_,b,&mr);uint32_t ti=0;if(!findType(mr.memoryTypeBits,props,ti,e)){vkDestroyBuffer(device_,b,nullptr);b=VK_NULL_HANDLE;return false;}VkMemoryAllocateInfo ai{VK_STRUCTURE_TYPE_MEMORY_ALLOCATE_INFO};ai.allocationSize=mr.size;ai.memoryTypeIndex=ti;r=vkAllocateMemory(device_,&ai,nullptr,&mem);if(r!=VK_SUCCESS){e="vkAllocateMemory: "+vr(r);vkDestroyBuffer(device_,b,nullptr);b=VK_NULL_HANDLE;return false;}r=vkBindBufferMemory(device_,b,mem,0);if(r!=VK_SUCCESS){e="vkBindBufferMemory: "+vr(r);vkFreeMemory(device_,mem,nullptr);vkDestroyBuffer(device_,b,nullptr);mem=VK_NULL_HANDLE;b=VK_NULL_HANDLE;return false;}return true;}
bool VulkanMemoryAllocator::createDeviceLocal(VkDeviceSize size,VkBufferUsageFlags usage,VkBuffer& b,VkDeviceMemory& m,std::string&e)const{return create(size,usage|VK_BUFFER_USAGE_TRANSFER_DST_BIT|VK_BUFFER_USAGE_TRANSFER_SRC_BIT,VK_MEMORY_PROPERTY_DEVICE_LOCAL_BIT,b,m,e);}
bool VulkanMemoryAllocator::createStaging(VkDeviceSize size,VkBuffer& b,VkDeviceMemory&m,std::string&e)const{return create(size,VK_BUFFER_USAGE_TRANSFER_SRC_BIT|VK_BUFFER_USAGE_TRANSFER_DST_BIT,VK_MEMORY_PROPERTY_HOST_VISIBLE_BIT|VK_MEMORY_PROPERTY_HOST_COHERENT_BIT,b,m,e);}
void VulkanMemoryAllocator::destroy(VkDevice d,VkBuffer&b,VkDeviceMemory&m){if(d){if(b)vkDestroyBuffer(d,b,nullptr);if(m)vkFreeMemory(d,m,nullptr);}b=VK_NULL_HANDLE;m=VK_NULL_HANDLE;}
}
